seed: 42

# Models are instantiated using skrl's model instantiator utility
# https://skrl.readthedocs.io/en/develop/api/utils/model_instantiators.html
models:
  separate: True
  policy:  # see 'skrl.utils.model_instantiators.torch.gaussian_model' for parameter details
    clip_actions: False
    clip_log_std: True
    initial_log_std: 0
    min_log_std: -20.0
    max_log_std: 2.0
    input_shape: "Shape.STATES"
    hiddens: [256, 128, 64]
    hidden_activation: ["elu", "elu", "elu"]
    output_shape: "Shape.ACTIONS"
    output_activation: ""
    output_scale: 1.0
    rnn_hidden_size: 128
    rnn_num_layers: 1
    rnn_sequence_length: 16
  value:  # see 'skrl.utils.model_instantiators.torch.deterministic_model' for parameter details
    clip_actions: False
    input_shape: "Shape.STATES"
    hiddens: [256, 128, 64]
    hidden_activation: ["elu", "elu", "elu"]
    output_shape: "Shape.ONE"
    output_activation: ""
    output_scale: 1.0
    rnn_hidden_size: 128
    rnn_num_layers: 1
    rnn_sequence_length: 16


# PPO agent configuration (field names are from PPO_DEFAULT_CONFIG)
# https://skrl.readthedocs.io/en/latest/api/agents/ppo.html
agent:
  rollouts: 16
  learning_epochs: 8
  mini_batches: 8
  discount_factor: 0.99
  lambda: 0.95
  learning_rate: 5.e-4
  learning_rate_scheduler: "KLAdaptiveLR"
  learning_rate_scheduler_kwargs:
    kl_threshold: 0.008
  state_preprocessor: "RunningStandardScaler"
  state_preprocessor_kwargs: null
  value_preprocessor: "RunningStandardScaler"
  value_preprocessor_kwargs: null
  random_timesteps: 0
  learning_starts: 0
  grad_norm_clip: 1.0
  ratio_clip: 0.2
  value_clip: 0.2
  clip_predicted_values: True
  entropy_loss_scale: 0.0
  value_loss_scale: 2.0
  kl_threshold: 0
  rewards_shaper_scale: 0.01
  # logging and checkpoint
  experiment:
    directory: "exploration_direct"
    experiment_name: ""
    write_interval: 120
    checkpoint_interval: 120
    wandb: True             # whether to use Weights & Biases
    wandb_kwargs:
      project: "isaac-sim-exploration"
      name: "" # wandb kwargs (see https://docs.wandb.ai/ref/python/init)

prop_estimator: 
  input_size: 7 # 11  # State and action concatenated size
  hidden_size: 64    # Number of features in hidden state
  num_layers: 1      # Number of LSTM layers
  output_size: 1     # Number of physical properties (e.g., friction, CoM)
  learning_rate: 0.001
  num_epochs: 5
  policy_switch: False
  # First iteration
  # pre_trained: False
  # freeze_weights: False
  # First iteration (eval)
  pre_trained: True
  # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-17_18-31-10/checkpoints_prop/LSTM_best.pth"
  # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-18_17-33-32/checkpoints_prop/LSTM_best.pth"
  # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-20_22-13-43/checkpoints_prop/LSTM_best.pth"
  pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-23_11-20-04/checkpoints_prop/LSTM_best.pth"
  freeze_weights: True
  # Second iteration 
  # pre_trained: True
  # # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-17_18-31-10/checkpoints_prop/LSTM_best.pth"
  # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-18_17-33-32/checkpoints_prop/LSTM_best.pth"
  # freeze_weights: False
  # Second iteration (eval)
  # pre_trained: True
  # # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-17_21-28-03/checkpoints_prop/LSTM_best.pth"
  # pre_trained_path: "/workspace/isaaclab/logs/skrl/exploration_direct/2024-10-18_18-27-53/checkpoints_prop/LSTM_best.pth"
  # freeze_weights: True

  position_index: [0,1,3,4]
  rotation_index: 2
  velocity_index: [5,6]
  # pos_min: -2.0
  # pos_max: 2.0
  # rot_min: -1.0
  # rot_max: 1.0
  # vel_min: -2.5
  # vel_max: 2.5
  # feature_target_min: -0.9
  # feature_target_max: 0.9
  pos_min: 0.4005
  pos_max: 0.9458
  rot_min: -1.0000
  rot_max: 0.9496
  vel_min: -1.6837
  vel_max: 1.1272
  feature_target_min: -0.9
  feature_target_max: 0.9

  fric_max: 0.3 # 1.0
  fric_min: 0.05 # 0.0
  estimate_target_min: -0.9
  estimate_target_max: 0.9

  # fric_min


# Sequential trainer
# https://skrl.readthedocs.io/en/latest/api/trainers/sequential.html
trainer:
  timesteps: 500000000 # 24000
  environment_info: "log"
